name: Android imgpatchtools

on:
  workflow_dispatch:
    inputs:
      FIRMWARE_FILE_URL:
        description: 'FIRMWARE_FILE_URL to download firmware'
        required: true
        default: 'wwwww'

      OTA_FILE_URL:
        description: 'OTA_FILE_URL to download firmware'
        required: true
        default: 'http://fota-secure-dn.ospserver.net:80/firmware/EUX/SM-S906B/nspx/104d0a8a8f404c62a52e908c8d18d437.bin?px-time=68050eef&px-hash=01c0f4875671edfe1543abee3fe76746&px-wid=5118064-WSA250417151244&px-wctime=2025-04-17%2015:12:44&px-cc=EUX&px-mn=SM-S906B&px-aid=EUX&px-nb=UGtezEZ854jbmFcvWGxLEA==&px-rmtime=2025-04-17%2015:14:52'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout code
        uses: actions/checkout@v2

      - name: 2️⃣ Installing packages.
        run: |
          cd && sudo apt-get update && sudo apt install p7zip-full lz4 android-sdk-libsparse-utils wget python3 -y git zlib1g-dev libbz2-dev libssl-dev && sudo pip3 install liblp

      
