name: Android imgpatchtools

on:
  workflow_dispatch:
    inputs:
      FIRMWARE_FILE_URL:
        description: 'FIRMWARE_FILE_URL to download firmware'
        required: true
        default: 'https://24x7-mltb.eu.org/0:findpath?id=1RxNhgJKrkwhmvL62NThm7X6HzfGurOHF'

      OTA_FILE_URL:
        description: 'OTA_FILE_URL to download firmware'
        required: true
        default: 'http://fota-secure-dn.ospserver.net:80/firmware/EUX/SM-S906B/nspx/104d0a8a8f404c62a52e908c8d18d437.bin?px-time=68050eef&px-hash=01c0f4875671edfe1543abee3fe76746&px-wid=5118064-WSA250417151244&px-wctime=2025-04-17%2015:12:44&px-cc=EUX&px-mn=SM-S906B&px-aid=EUX&px-nb=UGtezEZ854jbmFcvWGxLEA==&px-rmtime=2025-04-17%2015:14:52'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing packages.
        run: |
          cd && sudo apt-get update && sudo apt install p7zip-full lz4 android-sdk-libsparse-utils wget python3 -y git zlib1g-dev libbz2-dev libssl-dev && sudo pip3 install liblp

      - name: Downloading firmware.
        run: |
           cd && wget -O firmware.zip --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" ${{ github.event.inputs.FIRMWARE_FILE_URL }}

      - name: Extracting firmware.
        run: |
           cd && sudo 7z x firmware.zip && sudo rm -rf *.zip && sudo rm -rf *.txt && for file in *.md5; do sudo mv -- "$file" "${file%.md5}"; done && for file in *.tar; do sudo tar -xvf "$file"; done && sudo rm -rf *.tar && sudo rm -rf *.pit && sudo rm -rf meta-data && for file in *.lz4; do sudo lz4 -d "$file" "${file%.lz4}"; done && sudo rm -rf *.lz4 && sudo rm -rf *.bin && sudo find . -type f ! -name "*.img" -exec sudo rm -f {} + && sudo rm -rf boot.img cache.img dtbo.img ldfw.img omr.img recovery.img ssp.img tzar.img tzfw.img META-INF tzsw.img vbmeta.img vbmeta_system.img vendor_boot.img && sudo simg2img super.img super_raw.img && sudo rm -rf super.img && sudo mv super_raw.img super.img && sudo lpunpack super.img && sudo rm -rf super.img

      - name: File lis.
        run: |
           cd && ls
      
      - name: Downloading ota file.
        run: |
           cd && sudo rm -rf ota && sudo mkdir ota && cd ota && sudo wget -O ota_update.bin --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" "${{ github.event.inputs.OTA_FILE_URL }}"

      - name: Extracting ota file.
        run: |
           cd && cd ota && sudo 7z x ota_update.bin && sudo find . -type f ! \( -name "*.dat" -o -name "*.list" -o -name "*.img" \) -exec sudo rm -f {} + && sudo rm -rf boot.img cache.img dtbo.img ldfw.img omr.img recovery.img ssp.img tzar.img tzfw.img META-INF tzsw.img vbmeta.img vbmeta_system.img vendor_boot.img && sudo find . -maxdepth 1 -type f -exec sudo mv {} "$HOME" \; && cd && sudo rm -rf ota
